name: terminal_launcher
description: A minimalist command-line interface launcher for Android mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_apps: ^2.2.0
  device_info_plus: ^9.0.3
  battery_plus: ^4.0.2
  collection: ^1.16.0
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.4.2
  url_launcher: ^6.0.20
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_screen.png  

flutter_native_splash:
  color: "#000000"
  image: assets/splash_screen.png
  android_12:
